### ISSUE TITLE
Review Linear Algebra (9/11/21)

### ISSUE THREAD

**Issue by ahy69195** [ahy69195/AlbertYou_TasksQRG#3]
Review linear algebra

**Comment by ahy69195** [comment]
Let A be an m x n matrix. Then the following statements are logically equivalent. That is, for a particular A, either they are all true statements or they are all false.
a. For each b in R^m, the equation A x = b has a solution.
b. Each b in R^m is a linear combination of the columns of A. 
c. The columns of A span R^m.
d. A has a pivot position in every row.

Why does A have to have a pivot position in every row?

**Comment by ahy69195** [comment]
Wait nvm, I figured it out. This only applies if the Ax = b fulfills all b in the space R^m, so that is why A has to have a pivot position in every row; if there wasn't a pivot position in every row, the "columns of A could not span R^m" (every b in R^m is a linear combination of the columns of A). This is also just a coefficient matrix, not augmented*.

**Comment by Micky774** [comment]
Question for you: Suppose that we have a matrix `A` that satisfies statement `c)`. Does that imply that the inverse of `A` exists? Why or why not? In particular, when _does_ the inverse of A exist. Try not to just google this, and frame the response wrt to the statements `a-d` that are listed above.
